CREATE TABLE IF NOT EXISTS google_places_text_search_cache (
    cache_key VARCHAR(255) NOT NULL PRIMARY KEY,
    text_query VARCHAR(512) NOT NULL,
    city VARCHAR(128) NULL,
    response_json JSON NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
